import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'app.name': 'KeyManager.io',
    'nav.home': 'Accueil',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.blog': 'Blog',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',
    'dashboard.keys': 'Clés',
    'dashboard.properties': 'Biens',
    'dashboard.movements': 'Mouvements',
    'dashboard.users': 'Utilisateurs',
    'dashboard.settings': 'Paramètres',
    'dashboard.profile': 'Profil',
    'dashboard.agency': 'Agence',
    'dashboard.subscription': 'Abonnement',
    'dashboard.revenue': 'Revenus',
    'dashboard.stats': 'Statistiques',
    'dashboard.contacts': 'Contacts',
    'dashboard.announcements': 'Annonces',
    'dashboard.branding': 'Personnalisation',
    'dashboard.sms': 'Configuration SMS',
    'dashboard.blog': 'Gestion du blog',
    'dashboard.site-content': 'Contenu du site',
    'dashboard.super-admin': 'Super Admin',
    'dashboard.menu-order': 'Ordre du menu',
    'dashboard.stripe-config': 'Configuration Stripe',
    'dashboard.plans': 'Gestion des plans',
    'dashboard.purchase-orders': 'Bons de commande',
    'auth.login.title': 'Connexion',
    'auth.login.email': 'Email',
    'auth.login.password': 'Mot de passe',
    'auth.login.submit': 'Se connecter',
    'auth.login.no-account': 'Pas encore de compte ?',
    'auth.login.signup-link': 'Inscrivez-vous',
    'auth.login.subtitle': 'Accédez à votre espace de gestion',
    'auth.signup.title': 'Inscription',
    'auth.signup.agency-name': 'Nom de l\'agence',
    'auth.signup.first-name': 'Prénom',
    'auth.signup.last-name': 'Nom',
    'auth.signup.email': 'Email',
    'auth.signup.password': 'Mot de passe',
    'auth.signup.submit': 'Créer mon compte',
    'auth.signup.has-account': 'Déjà un compte ?',
    'auth.signup.login-link': 'Connectez-vous',
    'auth.signup.subtitle': 'Commencez gratuitement avec 10 clés',
    'auth.signup.password-error': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.signup.google': 'Continuer avec Google',
    'auth.login.google': 'Continuer avec Google',
    'auth.or': 'Ou continuer avec',
    'loading': 'Chargement...',
    'loading.connecting': 'Connexion en cours...',
    'loading.session': 'Récupération de vos informations de session',
    'error.connection': 'Problème de connexion détecté',
    'error.check-internet': 'Vérifiez votre connexion internet ou videz le cache si le problème persiste',
    'action.clear-cache': 'Vider le cache et redémarrer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'home.hero.badge': '🎉 Alertes SMS automatiques !',
    'home.hero.title': 'Plus jamais de clés perdues 🔑',
    'home.hero.subtitle': 'La solution ultra-simple pour gérer vos clés immobilières. Traçabilité magique, alertes automatiques et équipe synchronisée !',
    'home.hero.cta-primary': 'Essayer gratuitement',
    'home.hero.cta-secondary': 'Voir la magie ✨',
    'home.hero.free': '100% gratuit',
    'home.hero.secure': 'Sécurisé',
    'home.hero.setup': 'Setup 2 min',
    'home.hero.satisfaction': 'De satisfaction 🎊',
    'home.hero.agencies': 'Agences',
    'home.references.badge': '🏆 Ils nous font confiance',
    'home.features.badge': '✨ SUPER POUVOIRS',
    'home.features.title': 'Pourquoi c\'est génial ?',
    'home.features.subtitle': 'Des fonctionnalités qui vont vous faire gagner des heures chaque semaine',
    'home.features.feature1.title': 'Gestion centralisée 🎯',
    'home.features.feature1.desc': 'Toutes vos clés en un clic. Codes d\'accès, statuts en temps réel. Simple et efficace !',
    'home.features.feature2.title': 'Traçabilité magique 🔍',
    'home.features.feature2.desc': 'Qui a pris quoi ? Quand ? Pourquoi ? Tout est tracé automatiquement. Zéro effort !',
    'home.features.feature3.title': 'Alertes SMS 📱',
    'home.features.feature3.desc': 'Notifications automatiques en cas de retard. Ne perdez plus jamais vos clés !',
    'home.features.feature4.title': 'Équipe synchronisée 👥',
    'home.features.feature4.desc': 'Rôles et permissions pour toute votre équipe. Tout le monde est dans la boucle !',
    'home.testimonials.badge': '⭐ TÉMOIGNAGES',
    'home.testimonials.title': 'Ils sont fans ! 🤩',
    'home.testimonials.subtitle': 'Des milliers d\'agences conquises',
    'home.cta.badge': '🎉 Offre de lancement !',
    'home.cta.title': 'Prêt à révolutionner votre gestion des clés ?',
    'home.cta.subtitle': 'Rejoignez plus de 500 agences immobilières qui ont déjà simplifié leur quotidien avec KeyManager',
    'home.cta.primary': 'Commencer gratuitement',
    'home.cta.secondary': 'Voir les tarifs',
    'home.cta.free': '✨ 100% gratuit',
    'home.cta.no-commitment': '🚀 Sans engagement',
    'home.cta.quick-setup': '⚡ Setup 2 min',
    'branded.service': 'Un service KeyManager.io',
    'branded.employee-space': 'Espace Collaborateur',
    'branded.no-account': 'Vous n\'avez pas de compte ?',
    'branded.contact-admin': 'Contactez votre administrateur',
    'branded.access-restricted': 'Accès réservé aux collaborateurs de',
  },
  en: {
    'app.name': 'KeyManager.io',
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.blog': 'Blog',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'dashboard.keys': 'Keys',
    'dashboard.properties': 'Properties',
    'dashboard.movements': 'Movements',
    'dashboard.users': 'Users',
    'dashboard.settings': 'Settings',
    'dashboard.profile': 'Profile',
    'dashboard.agency': 'Agency',
    'dashboard.subscription': 'Subscription',
    'dashboard.revenue': 'Revenue',
    'dashboard.stats': 'Statistics',
    'dashboard.contacts': 'Contacts',
    'dashboard.announcements': 'Announcements',
    'dashboard.branding': 'Branding',
    'dashboard.sms': 'SMS Configuration',
    'dashboard.blog': 'Blog Management',
    'dashboard.site-content': 'Site Content',
    'dashboard.super-admin': 'Super Admin',
    'dashboard.menu-order': 'Menu Order',
    'dashboard.stripe-config': 'Stripe Configuration',
    'dashboard.plans': 'Plans Management',
    'dashboard.purchase-orders': 'Purchase Orders',
    'auth.login.title': 'Login',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.submit': 'Sign In',
    'auth.login.no-account': 'Don\'t have an account?',
    'auth.login.signup-link': 'Sign up',
    'auth.login.subtitle': 'Access your management dashboard',
    'auth.signup.title': 'Sign Up',
    'auth.signup.agency-name': 'Agency Name',
    'auth.signup.first-name': 'First Name',
    'auth.signup.last-name': 'Last Name',
    'auth.signup.email': 'Email',
    'auth.signup.password': 'Password',
    'auth.signup.submit': 'Create Account',
    'auth.signup.has-account': 'Already have an account?',
    'auth.signup.login-link': 'Sign in',
    'auth.signup.subtitle': 'Start for free with 10 keys',
    'auth.signup.password-error': 'Password must contain at least 6 characters',
    'auth.signup.google': 'Continue with Google',
    'auth.login.google': 'Continue with Google',
    'auth.or': 'Or continue with',
    'branded.service': 'A KeyManager.io service',
    'branded.employee-space': 'Employee Portal',
    'branded.no-account': 'Don\'t have an account?',
    'branded.contact-admin': 'Contact your administrator',
    'branded.access-restricted': 'Access restricted to employees of',
    'loading': 'Loading...',
    'loading.connecting': 'Connecting...',
    'loading.session': 'Retrieving your session information',
    'error.connection': 'Connection problem detected',
    'error.check-internet': 'Check your internet connection or clear cache if the problem persists',
    'action.clear-cache': 'Clear cache and restart',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.yes': 'Yes',
    'common.no': 'No',
    'home.hero.badge': '🎉 Automatic SMS alerts!',
    'home.hero.title': 'Never lose keys again 🔑',
    'home.hero.subtitle': 'The ultra-simple solution for managing your real estate keys. Magic traceability, automatic alerts and synchronized team!',
    'home.hero.cta-primary': 'Try for free',
    'home.hero.cta-secondary': 'See the magic ✨',
    'home.hero.free': '100% free',
    'home.hero.secure': 'Secure',
    'home.hero.setup': '2 min setup',
    'home.hero.satisfaction': 'Satisfaction 🎊',
    'home.hero.agencies': 'Agencies',
    'home.references.badge': '🏆 They trust us',
    'home.features.badge': '✨ SUPER POWERS',
    'home.features.title': 'Why is it awesome?',
    'home.features.subtitle': 'Features that will save you hours every week',
    'home.features.feature1.title': 'Centralized management 🎯',
    'home.features.feature1.desc': 'All your keys in one click. Access codes, real-time status. Simple and efficient!',
    'home.features.feature2.title': 'Magic traceability 🔍',
    'home.features.feature2.desc': 'Who took what? When? Why? Everything is tracked automatically. Zero effort!',
    'home.features.feature3.title': 'SMS alerts 📱',
    'home.features.feature3.desc': 'Automatic notifications in case of delay. Never lose your keys again!',
    'home.features.feature4.title': 'Synchronized team 👥',
    'home.features.feature4.desc': 'Roles and permissions for your entire team. Everyone is in the loop!',
    'home.testimonials.badge': '⭐ TESTIMONIALS',
    'home.testimonials.title': 'They love it! 🤩',
    'home.testimonials.subtitle': 'Thousands of agencies conquered',
    'home.cta.badge': '🎉 Launch offer!',
    'home.cta.title': 'Ready to revolutionize your key management?',
    'home.cta.subtitle': 'Join over 500 real estate agencies that have already simplified their daily life with KeyManager',
    'home.cta.primary': 'Start for free',
    'home.cta.secondary': 'See pricing',
    'home.cta.free': '✨ 100% free',
    'home.cta.no-commitment': '🚀 No commitment',
    'home.cta.quick-setup': '⚡ 2 min setup',
  },
  es: {
    'app.name': 'KeyManager.io',
    'nav.home': 'Inicio',
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.blog': 'Blog',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.logout': 'Cerrar sesión',
    'dashboard.keys': 'Llaves',
    'dashboard.properties': 'Propiedades',
    'dashboard.movements': 'Movimientos',
    'dashboard.users': 'Usuarios',
    'dashboard.settings': 'Configuración',
    'dashboard.profile': 'Perfil',
    'dashboard.agency': 'Agencia',
    'dashboard.subscription': 'Suscripción',
    'dashboard.revenue': 'Ingresos',
    'dashboard.stats': 'Estadísticas',
    'dashboard.contacts': 'Contactos',
    'dashboard.announcements': 'Anuncios',
    'dashboard.branding': 'Marca',
    'dashboard.sms': 'Configuración SMS',
    'dashboard.blog': 'Gestión del blog',
    'dashboard.site-content': 'Contenido del sitio',
    'dashboard.super-admin': 'Super Admin',
    'dashboard.menu-order': 'Orden del menú',
    'dashboard.stripe-config': 'Configuración Stripe',
    'dashboard.plans': 'Gestión de planes',
    'dashboard.purchase-orders': 'Órdenes de compra',
    'auth.login.title': 'Iniciar sesión',
    'auth.login.email': 'Correo electrónico',
    'auth.login.password': 'Contraseña',
    'auth.login.submit': 'Iniciar sesión',
    'auth.login.no-account': '¿No tienes una cuenta?',
    'auth.login.signup-link': 'Regístrate',
    'auth.login.subtitle': 'Accede a tu panel de gestión',
    'auth.signup.title': 'Registrarse',
    'auth.signup.agency-name': 'Nombre de la agencia',
    'auth.signup.first-name': 'Nombre',
    'auth.signup.last-name': 'Apellido',
    'auth.signup.email': 'Correo electrónico',
    'auth.signup.password': 'Contraseña',
    'auth.signup.submit': 'Crear cuenta',
    'auth.signup.has-account': '¿Ya tienes una cuenta?',
    'auth.signup.login-link': 'Inicia sesión',
    'auth.signup.subtitle': 'Comienza gratis con 10 llaves',
    'auth.signup.password-error': 'La contraseña debe contener al menos 6 caracteres',
    'auth.signup.google': 'Continuar con Google',
    'auth.login.google': 'Continuar con Google',
    'auth.or': 'O continuar con',
    'branded.service': 'Un servicio de KeyManager.io',
    'branded.employee-space': 'Portal de empleados',
    'branded.no-account': '¿No tienes una cuenta?',
    'branded.contact-admin': 'Contacta a tu administrador',
    'branded.access-restricted': 'Acceso restringido a empleados de',
    'loading': 'Cargando...',
    'loading.connecting': 'Conectando...',
    'loading.session': 'Recuperando tu información de sesión',
    'error.connection': 'Problema de conexión detectado',
    'error.check-internet': 'Verifica tu conexión a internet o borra la caché si el problema persiste',
    'action.clear-cache': 'Borrar caché y reiniciar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.yes': 'Sí',
    'common.no': 'No',
    'home.hero.badge': '🎉 ¡Alertas SMS automáticas!',
    'home.hero.title': 'Nunca más pierdas llaves 🔑',
    'home.hero.subtitle': '¡La solución ultra simple para gestionar tus llaves inmobiliarias. Trazabilidad mágica, alertas automáticas y equipo sincronizado!',
    'home.hero.cta-primary': 'Prueba gratis',
    'home.hero.cta-secondary': 'Ver la magia ✨',
    'home.hero.free': '100% gratis',
    'home.hero.secure': 'Seguro',
    'home.hero.setup': 'Config. 2 min',
    'home.hero.satisfaction': 'Satisfacción 🎊',
    'home.hero.agencies': 'Agencias',
    'home.references.badge': '🏆 Confían en nosotros',
    'home.features.badge': '✨ SÚPER PODERES',
    'home.features.title': '¿Por qué es genial?',
    'home.features.subtitle': 'Funciones que te harán ahorrar horas cada semana',
    'home.features.feature1.title': 'Gestión centralizada 🎯',
    'home.features.feature1.desc': 'Todas tus llaves en un clic. Códigos de acceso, estados en tiempo real. ¡Simple y eficaz!',
    'home.features.feature2.title': 'Trazabilidad mágica 🔍',
    'home.features.feature2.desc': '¿Quién tomó qué? ¿Cuándo? ¿Por qué? Todo se rastrea automáticamente. ¡Cero esfuerzo!',
    'home.features.feature3.title': 'Alertas SMS 📱',
    'home.features.feature3.desc': 'Notificaciones automáticas en caso de retraso. ¡Nunca pierdas tus llaves!',
    'home.features.feature4.title': 'Equipo sincronizado 👥',
    'home.features.feature4.desc': 'Roles y permisos para todo tu equipo. ¡Todos están al tanto!',
    'home.testimonials.badge': '⭐ TESTIMONIOS',
    'home.testimonials.title': '¡Les encanta! 🤩',
    'home.testimonials.subtitle': 'Miles de agencias conquistadas',
    'home.cta.badge': '🎉 ¡Oferta de lanzamiento!',
    'home.cta.title': '¿Listo para revolucionar tu gestión de llaves?',
    'home.cta.subtitle': 'Únete a más de 500 agencias inmobiliarias que ya han simplificado su día a día con KeyManager',
    'home.cta.primary': 'Comenzar gratis',
    'home.cta.secondary': 'Ver precios',
    'home.cta.free': '✨ 100% gratis',
    'home.cta.no-commitment': '🚀 Sin compromiso',
    'home.cta.quick-setup': '⚡ Config. 2 min',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('app-language');
    return (stored === 'en' || stored === 'fr' || stored === 'es') ? stored : 'fr';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
